version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "95:4c:f9:3f:1e:5e:60:e6:50:4f:b8:3f:a1:7e:58:c0"
      - run: git reset --hard
      - run: git pull
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - run: scp -r -o StrictHostKeyChecking=no dist/* root@198.211.112.212:/var/www/blmmorristown/dist/
workflows:
  build:
    jobs:
      - build
