version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "53:e9:1a:71:cf:11:fd:ac:21:d2:b9:fb:dd:33:0d:b9"
      - run: git reset --hard
      - run: git pull
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
workflows:
  build:
    jobs:
      - build
# These commands are triggered only after a successful (green) build.
deployment:
  dev:
    branch: master
    commands:
      - ssh root@198.211.112.212 'cd /var/www/blmmorristown && git pull && npm run build'
